-- CRIA BANCO DE DADOS
-- CREATE DATABASE PEDIDOSONLINE;

-- CRIA SCHEMA USUARIO;

CREATE SCHEMA IF NOT EXISTS USUARIO;
SET SCHEMA USUARIO;

-- USUARIO.USUARIO DEFINITION

CREATE TABLE USUARIO.USUARIO (
    ID_USUARIO INT AUTO_INCREMENT NOT NULL,
    NO_USUARIO VARCHAR NOT NULL,
    EMAIL VARCHAR NOT NULL,
    SENHA VARCHAR NOT NULL,
    DT_ANIVERSARIO DATE NOT NULL,
    NR_DDD NUMERIC NOT NULL,
    NR_TELEFONE NUMERIC NOT NULL,
    NR_CPF VARCHAR NULL,
    PRIMARY KEY (ID_USUARIO)
);

-- USUARIO.ENDERECO DEFINITION

CREATE TABLE USUARIO.ENDERECO (
    ID_ENDERECO INT AUTO_INCREMENT NOT NULL,
    LOGRADOURO VARCHAR NOT NULL,
    CEP VARCHAR NOT NULL,
    BAIRRO VARCHAR NOT NULL,
    COMPLEMENTO VARCHAR NULL,
    NUMERO VARCHAR NOT NULL,
    PRIMARY KEY (ID_ENDERECO)
);

-- USUARIO.ENDERECO_USUARIO DEFINITION

CREATE TABLE USUARIO.ENDERECO_USUARIO (
    ID_USUARIO INT NOT NULL,
    ID_ENDERECO INT NOT NULL,
    FOREIGN KEY (ID_ENDERECO) REFERENCES USUARIO.ENDERECO(ID_ENDERECO),
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO.USUARIO(ID_USUARIO)
);

-- DROP SCHEMA PEDIDO;

CREATE SCHEMA IF NOT EXISTS PEDIDO;
SET SCHEMA PEDIDO;

CREATE TABLE PEDIDO.CATEGORIA (
    ID_CATEGORIA INT AUTO_INCREMENT NOT NULL,
    NO_CATEGORIA VARCHAR NOT NULL,
    ID_CATEGORIA_PAI INTEGER NULL,
    PRIMARY KEY (ID_CATEGORIA),
    FOREIGN KEY (ID_CATEGORIA_PAI) REFERENCES PEDIDO.CATEGORIA(ID_CATEGORIA)
);

-- PEDIDO.PRODUTO DEFINITION

CREATE TABLE PEDIDO.PRODUTO (
    ID_PRODUTO INT AUTO_INCREMENT NOT NULL,
    NO_PRODUTO VARCHAR NOT NULL,
    VL_COMPRA DOUBLE NOT NULL,
    VL_VENDA DOUBLE NOT NULL,
    DS_PRODUTO VARCHAR NOT NULL,
    VL_PROMOCAO DOUBLE NULL,
    NO_IMAGEM VARCHAR NULL,
    ID_CATEGORIA INTEGER NOT NULL,
    PRIMARY KEY (ID_PRODUTO),
    FOREIGN KEY (ID_CATEGORIA) REFERENCES PEDIDO.CATEGORIA(ID_CATEGORIA)
);

-- PEDIDO.FORMA_PAGAMENTO DEFINITION

CREATE TABLE PEDIDO.FORMA_PAGAMENTO (
    ID_FORMA_PAGAMENTO INT AUTO_INCREMENT NOT NULL,
    NO_FORMA_PAGAMENTO VARCHAR NULL,
    PRIMARY KEY (ID_FORMA_PAGAMENTO)
);

-- PEDIDO.PEDIDO DEFINITION

CREATE TABLE PEDIDO.PEDIDO (
    ID_PEDIDO INT AUTO_INCREMENT NOT NULL,
    ID_USUARIO INT NOT NULL,
    DT_PEDIDO TIMESTAMP NOT NULL,
    ID_ENDERECO INT NOT NULL,
    ST_PEDIDO CHAR(1) NOT NULL,
    PR_ENTREGA_INICIAL TIME NOT NULL,
    PR_ENTREGA_FINAL TIME NOT NULL,
    ID_FORMA_PAGAMENTO INT NOT NULL,
    PRIMARY KEY (ID_PEDIDO),
    FOREIGN KEY (ID_ENDERECO) REFERENCES USUARIO.ENDERECO(ID_ENDERECO),
    FOREIGN KEY (ID_FORMA_PAGAMENTO) REFERENCES PEDIDO.FORMA_PAGAMENTO(ID_FORMA_PAGAMENTO),
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO.USUARIO(ID_USUARIO)
);

-- PEDIDO.PEDIDO_PRODUTO DEFINITION

CREATE TABLE PEDIDO.PEDIDO_PRODUTO (
    ID_PEDIDO_PRODUTO INT AUTO_INCREMENT NOT NULL,
    ID_PEDIDO INT NOT NULL,
    ID_PRODUTO INT NOT NULL,
    NR_QUANTIDADE INT NOT NULL,
    OBSERVACAO VARCHAR NULL,
    PRIMARY KEY (ID_PEDIDO_PRODUTO),
    FOREIGN KEY (ID_PRODUTO) REFERENCES PEDIDO.PRODUTO(ID_PRODUTO),
    FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDO.PEDIDO(ID_PEDIDO)
);

ALTER TABLE usuario.endereco_usuario ADD id serial NOT NULL;
ALTER TABLE usuario.endereco_usuario ADD CONSTRAINT endereco_usuario_pk PRIMARY KEY (id);

